apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder
helmCharts:
- name: coder
  releaseName: coder-v2
  version: 2.17.2
  repo: https://helm.coder.com/v2
  namespace: coder
  valuesFile: ./values.yaml

resources:
- secrets
- namespace.yaml
- storageclass.yaml
- serviceaccount.yaml