apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: eretail
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        # HTTP_Server               On
        # HTTP_Listen               0.0.0.0
        # HTTP_Port                 2020
        
    @INCLUDE application-log.conf
  
  pod-log.conf: |
    [INPUT]
        Name                tail
        Path                /var/log/pods/*.log
        Tag                 boot.*
        Parser              docker
        Mem_Buf_Limit       5MB
        Refresh_Interval    10
        
    [OUTPUT]
        Name                cloudwatch
        Match               *boot*
        region              ap-southeast-1
        log_group_name      eks-fluent-bit
        log_stream_prefix   ${HOSTNAME}-boot-log-
        auto_create_group   true
        # workers             1
        
    [OUTPUT]
        Name                cloudwatch
        Match               *access*
        region              ap-southeast-1
        log_group_name      eks-fluent-bit
        log_stream_prefix   ${HOSTNAME}-access-log-
        auto_create_group   true
        # workers             1
        
  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZv