apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-provisioner
helmCharts:
- name: coder-provisioner
  releaseName: coder-provisioner
  version: 2.17.2
  repo: https://helm.coder.com/v2
  namespace: private-provisioner
  valuesFile: ./values.yaml

resources:
- secrets
- namespace.yaml
- serviceaccount.yaml