apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder
helmCharts:
- name: coder
  releaseName: coder-v2
  version: 2.15.0
  repo: https://helm.coder.com/v2
  namespace: coder
  valuesFile: ./values.yml
